### ISSUE TITLE
使用流程是…

### ISSUE THREAD

**Issue by linonetwo** [fguby/live2D#1]
1. 购买 Live2D 编辑器
2. 编辑并导出模型
3. 用这个加载

对吗？

例子里的阿黑颜不错

<img width="270" alt="屏幕快照 2019-06-04 下午9 34 24" src="https://user-images.githubusercontent.com/3746270/58883335-cc666580-8710-11e9-8b71-1a584d5926be.png">

**Comment by fguby** [comment]
更简单的办法是去找现成的模型下载就行，网上有很多不错的资源的~还有一种办法，就是找游戏，有的手游里的类似这样的模型也是可以用的，我就从手游里找到了很多模型。

**Comment by linonetwo** [comment]
话说现在编辑器有没有开源解决方案啊？
现在的情况居然是创作者要付钱，使用却不用付钱？我想在自己的小游戏里使用的。

**Comment by fguby** [comment]
编辑器的话应该有免费版吧？不过功能应该受限严重，正式版好像也有一个多月的试用期。不过如果想自己制作模型的话，确实比较麻烦。另外，模型的使用其实也会涉及到侵权吧（除非源作者同意），但只要你不是商用应该就无所谓，像上面例子里的小黑其实就是我从一款手游药水制作师里提取的。

**Comment by linonetwo** [comment]
嗯，谢谢解答

**Comment by doublingimba** [comment]
作者有联系方式吗。。太菜了不会装，哭了，

**Comment by fguby** [comment]
加我qq吧，541208156



    


            在2019年07月19日 18:38，doublingimba 写道： 作者有联系方式吗。。太菜了不会装，哭了，



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/fguby/live2D/issues/1?email_source=notifications\u0026email_token=AH5EHFPG5Z4RBUZPP5NJHZDQAGKQRA5CNFSM4HS4N2AKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2LIULY#issuecomment-513182255",

"url": "https://github.com/fguby/live2D/issues/1?email_source=notifications\u0026email_token=AH5EHFPG5Z4RBUZPP5NJHZDQAGKQRA5CNFSM4HS4N2AKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2LIULY#issuecomment-513182255",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
